services:
  weaviate:
    image: semitechnologies/weaviate:1.24.5
    # ports:
    expose:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
  ingest:
    build:
      context: . 
    ports:
    - 8000:8000
    - 8501:8501
    volumes:
    - llm_data:/data/:777
    environment:
      HF_HOME: '/data/huggingface'
      ROOT_PATH_FOR_DYNACONF: '/app/myexpertchat'
      MYEXPERTCHAT_WEAVIATE_URL: 'http://weaviate:8080'

    # command: gunicorn -b 0.0.0.0:8000 myexpertchat.ingest:app
    command: streamlit run frontend.py
    depends_on:
      - weaviate



    # volumes:
    # -model_cache:/home/user/.cache/huggingface
volumes:
  weaviate_data:
  llm_data: