services:
  weaviate:
    image: semitechnologies/weaviate:1.26.2
    ports:
    # expose:
    - 8080:8080
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      LIMIT_RESOURCES: 'true'
  ingest:
    build:
      context: . 
    ports:
    - 8000:8000
    - 8001:8001
    volumes:
    - llm_data:/data/:777
    environment:
      HF_HOME: '/data/huggingface'
      ROOT_PATH_FOR_DYNACONF: '/app/myexpertchat'
      MYEXPERTCHAT_WEAVIATE_URL: "http://weaviate:8080"
      PYTHONPATH: '/app'
    command: /bin/multirun "flask --app myexpertchat/ingest.py run --port 8001 --host 0.0.0.0" "streamlit run myexpertchat/frontend.py --server.port 8000"
    depends_on:
      - weaviate
volumes:
  weaviate_data:
  llm_data:
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]
    # volumes:
    # -model_cache:/home/user/.cache/huggingface
